contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #asseval channel"
    url: https://nfcore.slack.com/channels/asseval
    about: Discussion about the nf-core/asseval pipeline
